server:
  servlet:
    context-path: /xsy
#thymelea模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
#热部署文件，页面不产生缓存，及时更新
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**