server:
  servlet:
    context-path: /xsy
  port: 80
#thymelea模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  #热部署文件，页面不产生缓存，及时更新
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  #数据源配置
  datasource:
    url:
    hikari:
      username:
      password:
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
xsy:
  security:
    social:
      filterProcessesUrl: /qqLogin
      qq:
        app-id:
        app-secret:
      wechat:
        app-id:
        app-secret: